
import '@/app/ui/globals.css';
import { inter } from '@/app/ui/fonts';
import Footer from './ui/footer/footer';
import FinalHeader from './ui/header/decideHeader';
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};
export var color_them = 'dark'


export default function RootLayout({ children }: { children: React.ReactNode; }) {
    return (
        <html id='globalWEB' lang="en" className={color_them}>
            <head>
               
            </head>
            
            <body className={`${inter.className} antialiased e `} >
            <FinalHeader />
            <div style={{ minHeight: '800px', border: '2px solid red', padding: '10px', borderRadius:'5px' }}>
        {children}
      </div>
               
                    <Footer />
               

            </body>

        </html>


    );
}